

version: '3'

services:
  db:
    build: ./postgresql
    container_name: db
    expose:
      - "5432"
    ports:
      - "5432:5432"
  web:
    build: ./nodejs
    container_name: web
    command: npm run start
    environment:
      DB_HOST: db
    volumes:
      - "./nodejs/src:/usr/src/app/src"
    expose:
      - "3000"
    ports:
      - "8080:3000"
    depends_on:
      - db